#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QLabel>
#include "paintwidget.h"
#include "worker.h"

//generated by Qt Designer from mainwindow.ui form (see build-drawing-Desktop_Qt_5_3_MinGW_32bit-Debug/ui_mainwindow.h)
namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();

    bool Thread_status;
    parameters p;
    lattice *l;

//handlers that process incoming events
public slots:
    void button_clicked();
    void button_2_clicked();
    void paint_resized(QSize old_size, QSize new_size);
    void Recieve_data(int number);

signals:
    void SendDeleteThread();
    void SendPause();
    void SendRun();
    void close();

private slots:

private:
    Ui::MainWindow *ui;
    PaintWidget *paintWidget; //new dynamically created widget
    QLabel *lb1;
    QLabel *lb2;

    void draw_picture();
};

#endif // MAINWINDOW_H
