#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QLabel>
#include "paintwidget.h"
#include "worker.h"

//generated by Qt Designer from mainwindow.ui form (see build-drawing-Desktop_Qt_5_3_MinGW_32bit-Debug/ui_mainwindow.h)
namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();

    bool Thread_status;
    parameters p;
    lattice *l;

//handlers that process incoming events
public slots: //"slots" keyword is an extension of Qt framework
    void button_clicked();
    void button_2_clicked();
    //void beta_changed(double ch_beta);
    //void Time_to_close();
    void paint_resized(QSize old_size, QSize new_size);
    void Recieve_data(int number);
    //void Recieve_Thread_deleted();
    /*void paint_double_clicked(int x, int y);
    void paint_scrolled(int w, int x, int y);
    void paint_mouse_move(int x, int y);
    void paint_mouse_button_down(int x, int y);
    void paint_mouse_button_up();*/

signals:
    void SendDeleteThread();
    void SendPause();
    void SendRun();
    void close();
    //void Send_model(parameters, lattice*);

private slots:

private:
    Ui::MainWindow *ui;
    PaintWidget *paintWidget; //new dynamically created widget
    QLabel *lb1;
    QLabel *lb2;
    /*QLabel *lb3;
    QLabel *lb4;*/
    //bool can_draw; //flag
    /*int scale;
    int x0, y0;
    bool captured;
    int saved_x;
    int saved_y;
    int saved_x0;
    int saved_y0;*/
    void draw_picture();
};

#endif // MAINWINDOW_H
