#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include "hdr/paintwidget.h"
#include "hdr/ising_model.h"
#include <QMainWindow>
#include <QLabel>

//#define DEBUG

//generated by Qt Designer from mainwindow.ui form (see build-drawing-Desktop_Qt_5_3_MinGW_32bit-Debug/ui_mainwindow.h)
namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
	explicit MainWindow(int l_size = 64, QWidget *parent = 0);
    ~MainWindow();

	int alg; //simulation algorithm: 1 for heat_bath, -1 for clasters
	bool Thread_status; //true when thread is working, false when terminated
	parameters p; //parameters of the model
	int l_size; //square_lattice size - number of rows or columns
	lattice *l; //lattice type of square_lattice, used in simulation

public slots:
    void change_algo_label();
    void canvas_resized(QSize old_size, QSize new_size);
    void recieve_step(int number);

signals:
    void send_delete_thread();

private slots:

private:
    Ui::MainWindow *ui;
    PaintWidget *paintWidget; //new dynamically created widget
    QLabel *lb1;
    QLabel *lb2;
    QLabel *lb3;

    void draw_picture();
};

#endif // MAINWINDOW_H
